### ISSUE TITLE
UX Improvements

### ISSUE THREAD

**Issue by kyliechung** [holistic-web/home-orchestrator#17]
# Account Page: 
- After clicking the 'set active' button it could automatically switch to the light/theme page. This is to a show a more distinct confirmation on the site that the user has selected and been directed to the next page where the user can make changes to the lights. 

- The Accounts page should be the first page a user sees when going onto the orchestrator site, so the user won't think that the Lights page isn't loading, because they haven't yet activated which room they want to work in.

# Lights page:
- Although it is helpful that the distance between the buttons and the display icons makes them very clear from one another, they could be placed closer together to show more unity and it also would help to decrease the distance between clicking different icons and buttons across the page.

## The Refresh button:
- Not sure what it is for and also its call to action is unclear. 
I've realised that when this button is clicked, the lights are set to the first theme. However, I'm unsure what the use of that is unless theme no.1 is the most used lighting theme so the 'refresh' button can be used as a home button for the lighting. 

## The Update Lights button and the header that it is on:
- For better efficiency, the header could stay visible on the top of the site as the user scrolls down the pages. As of currently, the header moves up for example when the user scrolls down to select the changes for the lamp lights and then has to scroll back up to hit 'Update Lights'. 

# Themes page:
- The hex codes for the lights in themes can be tricky in guessing the colours. A thumbnail by the side of each theme to show the colour(s) could be helpful to visualise which theme to pick. 

- The Themes list could be on the same page as the Lights, such as by being a menu in the side of the Lights page. This is so users can edit and make new themes easier without having to switch back and forth between the two tabs to see what sets of colours there are.

**Comment by michaelfitzhavey** [comment]
This looks fantastic - thanks! A couple queries below:

> After clicking the 'set active' button it could automatically switch to the light/theme page. This is to a show a more distinct confirmation on the site that the user has selected and been directed to the next page where the user can make changes to the lights.

I totally agree we should make the act of setting a network more clear, but I'm not sure about redirecting users who may not be expecting to be taken off the current page. Perhaps the current network can be set by some sort of modal?

> The Accounts page should be the first page a user sees when going onto the orchestrator site, so the user won't think that the Lights page isn't loading, because they haven't yet activated which room they want to work in.

The issue here is that once a network has been selected we won't want a user to be navigated here, a solution could be redirecting any users who do not currently have a network selected to the account page?

> Refresh Button
I definitely agree it's confusing as is, the purpose of it is to load the current state of the lights from the database, for instance if the lights were updated from another device / by another user. These updates should probably be automated, especially if you think it's a priority for a user's experience.

> Themes list being to the side of lights
This sounds awesome, some UI help for what submenu's of pages should look like would be fab

**Comment by kyliechung** [comment]
I've updated the main issue!
> 
> > After clicking the 'set active' button it could automatically switch to the light/theme page. This is to a show a more distinct confirmation on the site that the user has selected and been directed to the next page where the user can make changes to the lights.
> 
> I totally agree we should make the act of setting a network more clear, but I'm not sure about redirecting users who may not be expecting to be taken off the current page. Perhaps the current network can be set by some sort of modal?

> 
> > The Accounts page should be the first page a user sees when going onto the orchestrator site, so the user won't think that the Lights page isn't loading, because they haven't yet activated which room they want to work in.
> 
> The issue here is that once a network has been selected we won't want a user to be navigated here, a solution could be redirecting any users who do not currently have a network selected to the account page?

I think the above two solutions you've given sounds like a good idea. We can always try it and see how it works. 
We should also keep in mind that a user who already is in a network might want to switch into another network, so perhaps we need to find a way to still have it accessible.
> 
> > Refresh Button
> 
> I definitely agree it's confusing as is, the purpose of it is to load the current state of the lights from the database, for instance if the lights were updated from another device / by another user. These updates should probably be automated, especially if you think it's a priority for a user's experience.

I think automating this would be so good for UX.
> 
> > Themes list being to the side of lights
> 
> This sounds awesome, some UI help for what submenus of pages should look like would be fab
Sure, I'll update on this issue when I make a visual mock representation of what I mean!

**Comment by michaelfitzhavey** [comment]
In light of the above, I think we should make the following work items to start with:

- have user select current network from modal

- if no network is currently set in the UI, redirect logged in users to the account page and prompt them to set on

- design new interface for setting a light

- adapt device view when changes are made to database

- add fixed header as taskbar at the bottom

- replace hex code/rgb with a sample cell displaying the selected colour

- UI for submenus and themes

Is there anything you think is missing from here?

**Comment by kyliechung** [comment]
I want to add one more thing! I noticed that the 'set active' button in the Accounts tab isn't clear that it has been clicked when it is. Other than that everything is good!

Also just to confirm from the list above that these designing tasks below here are mine to do:

- design new interface for setting a light

- add fixed header as taskbar at the bottom

- replace hex code/rgb with a sample cell displaying the selected colour (show by design how it should look)

- UI for submenus and themes

**Comment by michaelfitzhavey** [comment]
@kyliechung The set active not being clear when pressed should be fixed as setting a network will trigger the modal to close (part of #19).

Your above list sounds great, I've edited your comment to add the relevant issue number to each of your bullet points

**Comment by dan47bennett** [comment]
Regarding setting a network and which page to open on I believe this could be fixed by allowing a user to set a default network for their account. This would mean the user could be sent to the page to control lights with a network already active. I have opened #29 to explore this further.

**Comment by michaelfitzhavey** [comment]
In order to reduce clutter let's ensure we've made issues regarding everything in this discussion and then close this issue. I plan to do it in the best part of a week or so 🛩

**Comment by kyliechung** [comment]
All issues have been moved! I'm going to close this issue 😄
