### ISSUE TITLE
Creating themes Issue in the Known Issues page

### ISSUE THREAD

**Issue by kyliechung** [holistic-web/home-orchestrator#18]
hey I was just looking in the Known Issues page and I was wondering if this issue has been updated already? 

> creating a new theme takes you to the themes list page rather than the new theme's detail page

I tested out a new theme called 'Off - test' in Mike's room account and the process of making a new theme was fine. I selected the details, clicked on the New Theme button then it brought me into a pop up to name and save the theme. Finally, it brought me into the Themes list page. 
Perhaps this issue has been solved already, so it could be updated on the Known Issues page!

**Comment by michaelfitzhavey** [comment]
I agree, the original intent was to have it redirect to a new 'Theme Detail' page that only had information regarding the newly created theme but redirecting to the list feels more natural.

I'll make a change to remove that from the roadmap - thanks :)

**Comment by michaelfitzhavey** [comment]
A pull request to make this change exists at #26, can merge than and close this issue
