### ISSUE TITLE
New interface for controlling lights and Add Unify Lights Button

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/home-orchestrator#21]
Part of the work effort outlined in #17 

Blocked until issue #33  is done.

Currently the lights controls aren't great on either mobile or desktop. We want to create new designs for how to control the lights

Some notes:
- We want to use the tools available here: https://baianat.github.io/verte/examples.html#wheel-picker
- We want to be able to update lights individually
- Perhaps a mode where the lights update as soon as a colour is set?

Let's make a design first and then implement it and see how it works!

## Plan
- [x] replace current colourpicker with one from [new selection]( https://baianat.github.io/verte/examples.html#wheel-picker)
- [ ] design new light interface for mobile and desktop
- [ ] implement this new design
- [ ] deploy to live

**Comment by kyliechung** [comment]
ok! I'll get to designing some basic wireframes first then show you them to see what you think, which then will lead to higher fidelity designs! I'll keep you posted.  😄

**Comment by dan47bennett** [comment]
While the designs are being mocked up we're going to go ahead and swap our existing colourpicker for this one: https://github.com/baianat/verte.

We think it emulates the colour picker in the hue app and is generally cleaner and more user friendly.

Work in progress in #28.

**Comment by dan47bennett** [comment]
Examples are provided in the Verte documentation at https://baianat.github.io/verte/examples.html#default-example. Take a look at the current design for a more minimalist style.

**Comment by kyliechung** [comment]
### add a Unify all lights button onto each light

![IMG_1230](https://user-images.githubusercontent.com/45569851/63212805-31d8c880-c13c-11e9-9735-101093b4ddf4.JPG)

### aim:

- set all lights to the same setting (depending which light you click on)
- It does not send the update lights event, it only switches all the lights to the same value. The action has to go through the Update Lights button in the Action bar - a 2 step process. 
- disable Unify button if not possible, ie. light in a custom mode (for instance the nano leaf)


### future objectives
Create a toggle switch that allows the to switch between automatic and manual modes for updating the lights. It should hide the Action Bar if it is set to auto as it makes the buttons on the bar useless. This would also mean that users don't have to go through the 2 step process to unify all lights.
