### ISSUE TITLE
When controlling lights, show actions in a fixed Action Bar at the bottom

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/home-orchestrator#23]
This is part of the work effort outlined in #17

Currently users have to scroll to the top of the page to apply changes they have made, adding a fixed action bar will fix this.

Here's the XD link to the design. https://xd.adobe.com/spec/6cdf7089-5631-4ebf-505a-1b6a50b4efdf-1aee/

<img width="622" alt="Screen Shot 2019-08-16 at 22 09 46" src="https://user-images.githubusercontent.com/45569851/63173899-6df42680-c073-11e9-972d-c2c673a6cfa4.png">

## Plan
- [x] design what a fixed action bar could look like for the lights page on mobile and desktop
- [ ] implement this design
- [ ] deploy to live

### future objectives:
Create a toggle switch that allows to switch between automatic and manual modes for updating the lights. It should hide the Action Bar if it is set to auto, as it makes the buttons on the bar useless. This would also mean that users don't have to go through the 2 step process to unify all lights.

**Comment by kyliechung** [comment]
hey guys, i'm trying to figure out a easy looking design and I think that I'm going to merge the task bar into the navigation drawer menu on the side rather than a task

**Comment by kyliechung** [comment]
sorry just accidentally closed it :P

**Comment by kyliechung** [comment]
Hey here's a [link](https://xd.adobe.com/spec/53ca18e1-20bf-41f6-45af-572d03546492-25fb/) to the taskbar-footer! Let me know if there are any improvement suggestions/changes!

**Comment by kyliechung** [comment]
Progress update: this is a pic of some pen and paper wireframe designs. I'm going to base my design off the sketch with the star on it.

Currently I have the buttons: 

- Refresh

- Save As Theme

- Update Lights

- Change All Lights to the Same Colour *if anyone has a better idea of how to make this button's name more precise and shorter that would be really helpful!!


![IMG_3800](https://user-images.githubusercontent.com/45569851/63021727-d0aebc00-bed3-11e9-87ac-80fd86be9e5d.JPG)

**Comment by kyliechung** [comment]
so the best name I could think of so far is 'Unify All Colours'.

> * Change All Lights to the Same Colour *if anyone has a better idea of how to make this button's name more precise and shorter that would be really helpful!!

**Comment by kyliechung** [comment]
Here's the [link](https://xd.adobe.com/spec/53ca18e1-20bf-41f6-45af-572d03546492-25fb/) to the XD design for this issue!

as per let me know if there any suggestions! :D

**Comment by michaelfitzhavey** [comment]
The sidebar etc looks different at the moment, are we changing those too? Maybe worth putting that into a seperate task.

The taskbar itself looks so cool. A couple initial points:
- I'm not clear on what the functionality of clicking the `unify lights` button would do

- Maybe taskbar actions should only be for changing the lights? and small things like add to new theme could be in the top corner or somewhere else (I'm thinking similar to how google play music lets you control your music with a taskbar, and manage your library elsewhere)

**Comment by kyliechung** [comment]
I'd like to change them at some point, I'm not sure when that is a good time for you guys to do that though. I'll make a task for that.
As for now I will use a screenshot of the current orchestrator site as the background under the new design parts - and I'll re-edit the links where they look different. 

## To answer your points:

>I'm not clear on what the functionality of clicking the unify lights button would do

We spoke about creating a button that has a function to change all the lights to the same one colour, but I haven't planned how the users would be able to choose that one colour yet. 
>Maybe taskbar actions should only be for changing the lights? and small things like add to new theme could be in the top corner or somewhere else (I'm thinking similar to how google play music lets you control your music with a taskbar, and manage your library elsewhere)

my initial thought was that it wouldn't be great to put a button by itself on the top corner of the lights because there are a lot of buttons on the site already so I think that would be confusing if we put it out of the sectioned areas, so I'll need to plan where we can put it so it doesn't look lost. 

### Some initial solution ideas:
- in the sidebar where the themes palettes are already located
![IMG_1214](https://user-images.githubusercontent.com/45569851/63028060-a4e60300-bee0-11e9-8d3a-30cad3cfaa57.JPG)

## or
- on the left hand side of the action bar because the other actions are leaning onto the right. 
![IMG_1215](https://user-images.githubusercontent.com/45569851/63028047-a0b9e580-bee0-11e9-8fa3-7905b8a5085c.JPG)

(sorry about my picture quality - phone camera is a bit wack with its focus)

Let me know what you think is a better solution or if you have others!

**Comment by kyliechung** [comment]
here's an updated xd [link](https://xd.adobe.com/spec/79ca1135-5d87-4140-7872-7dc3e01f947f-0ffb/) with the screenshot at the back of the current orchestrator site. 

- I haven't had time to deal with the Save as Theme button moving somewhere else yet, as that was a raised issue about it not being part of the action bar. If we can be clear what goes into where, for this instance the action bar, that would make things a lot clearer. 

- remove the buttons (refresh and update lights button) on the top as they should be down in the task bar. (save as theme button is still on discussion)

**Comment by kyliechung** [comment]
### I thought to also include a sketch of how the sections in the lights page would look with the Taskbar and the Themes sidebar (issue #25) in it from 

This is to show that the Taskbar should not cut into the Themes Sidebar if this is the design we end up choosing to go with.
![IMG_1217](https://user-images.githubusercontent.com/45569851/63093484-04531a00-bf98-11e9-8d48-4360f652350d.JPG)

**Comment by michaelfitzhavey** [comment]
I think it looks great! Actions at the bottom look very professional.

Do you think we should add some colour to our buttons?

**Comment by kyliechung** [comment]
> Do you think we should add some colour to our buttons?

I've added [that](https://xd.adobe.com/spec/6cdf7089-5631-4ebf-505a-1b6a50b4efdf-1aee/) now! thanks for the suggestion

**Comment by michaelfitzhavey** [comment]
Sweet, a PR is in progress to add this here: https://github.com/holistic-web/home-orchestrator/pull/37

**Comment by michaelfitzhavey** [comment]
@kyliechung This has now been merged and deployed to live. If you don't think there are any other changes required on mobile or desktop lets close this issue 😃

**Comment by kyliechung** [comment]
@michaelfitzhavey Nice! I just had a look, there's one thing, I'm wondering if there is any reason why the Refresh Button is not in the action bar? 
Also I haven't done anything for the mobile design yet, just been focusing on the web design so far!

**Comment by michaelfitzhavey** [comment]
- refresh button has been left out as I thought we agreed action bar for for actions that have an effect on lights

- sure, I've just kept the colour it had previously for now

- unfortunately as the site works and is used on mobile we'll have to be aware of how changes to the site affect their user experience. For now it's ok I think I did ok with this one

**Comment by kyliechung** [comment]
@michaelfitzhavey 
>refresh button has been left out as I thought we agreed action bar for for actions that have an effect on lights

Ok, I didn't realise we had agreed on it - the button has been in many links and screenshots so I thought it wasn't a problem (apart from the Save As Theme button). So to clarify, the Update Lights button is the only button on the Action bar as of now?

>unfortunately as the site works and is used on mobile we'll have to be aware of how changes to the site affect their user experience. For now it's ok I think I did ok with this one

I'll try to get on with the mobile site design as soon as I can! I'll need assistance in downloading it again please.

**Comment by michaelfitzhavey** [comment]
Following on from the conversation on Facebook I think all is good to hide the refresh button / whatever you think is best. New designs are boss!

**Comment by kyliechung** [comment]
becus @michaelfitzhavey is a G for putting up the Action Bar even into the mobile site, I'm going to close this issue!
