### ISSUE TITLE
Display colour values using a palette rather than just hex / RGB value

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/home-orchestrator#24]
### Design for the use of palettes

Here's the XD link https://xd.adobe.com/spec/51785fd3-e4a4-4cb4-73ef-2e9d0f45f711-2749/

![Screenshot 2019-08-25 at 6 40 33 PM](https://user-images.githubusercontent.com/45569851/63648826-dde76880-c767-11e9-968e-d9bc05b4be8d.png)

Palette Interaction:
- When circle colours are hovered over they show the light's info

## Plan
- [x] design how the ideal palette should look and how we want to represent hex / rgb colour values
- [ ] implement design
- [ ] deploy to live

**Comment by dan47bennett** [comment]
Work is in progress using this API https://baianat.github.io/verte/api.html#props with the aim to emulate the look of Hue's own colour selector with a wheel picker and cleaner design.

**Comment by dan47bennett** [comment]
Examples are provided in the Verte documentation at https://baianat.github.io/verte/examples.html#default-example. Take a look at the current design for a more minimalist style.
