### ISSUE TITLE
Allow user to set a default network

### ISSUE THREAD

**Issue by dan47bennett** [holistic-web/home-orchestrator#29]
Currently the user has to go to the account page to pick a network, this could be improved by having a default network for a user so they could access their light control immediately upon opening the site.

## Plan
- [x] create a collection `users` in the database
- ~modify account creation so a `user` object is created for each new user~
- [x] create `user` objects for all existing users, and ensure `networkId` is set
- [x] add an endpoint to the orchestration-api to allow a user to update their network
- [x] change orchestration-ui to update current network by using this endpoint
- [x] clean up all code relating to storing the network locally
- [x] modify all requests to no longer take a `networkId` and instead use the `networkId` currently stored on the user object

These changes mean that a network will be set for a user 'globally', and as such will always be set no matter which device is used! 🎉 

## Further Work
- [x] create an issue to have a 'sign up' stage for new users (#36)

**Comment by michaelfitzhavey** [comment]
I agree, I think it would be much simpler if we had the user set their 'active network' by setting a prop in the database. 

User's can select a default network that is stored in the database also to be used when no network is selected.

It may be worth thinking about bundling this work with some other network items
- [ ] prompt users without a network to create one
- [ ] allow users to create multiple networks

**Comment by michaelfitzhavey** [comment]
#34 has been created to track the progress of this task

**Comment by michaelfitzhavey** [comment]
#34 has now been merged so we can close this 🎉
